version: '3.1'
services:
  etl:
    build: .
    image: sql-test-app
    container_name: etl
    depends_on:
      - db
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    volumes:
      - /python-app/data/db:/metabase-data
    ports:
      - "3000:3000"
#    environment:
#      MB_DB_TYPE: "mysql"
#      MB_DB_HOST: "sqldb" # sql db container_name
#      MB_DB_PORT: "3306"
#      MB_DB_NAME: "metabase"
#      MB_DB_DBNAME: "metabase"
#      MB_DB_USER: "dba"
#      MB_DB_PASS: "A1YTsqilzHkUQ4"
    depends_on:
      - db
# The --trustServerCertificate=true jdbc parameter should be used for the connection  
# But I don't know how to add this to the metabase container

#    secrets:
#      - db_credentials
  db:
    image: mysql:5.7
    container_name: sqldb
#    command: --default-authentication-plugin=mysql_native_password
#    command: --default-authentication-plugin=caching_sha2_password
    deploy:
#    ports:
#      - 3306:3306
    environment:
#      MYSQL_ROOT_PASSWORD: "EhTbmTtNS5KXO+U7"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: dba
      MYSQL_DATABASE: metabase    
      MYSQL_PASSWORD: "A1YTsqilzHkUQ4"
#    volumes:
#      - /Users/A347826/opt/docker/volumes/mysql:/var/lib/mysql

#  adminer:
#    image: adminer
#    ports:
#      - 8080:8080
