version: '3.1'
services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - /python-app/data/db:/metabase-data
    ports:
      - "3000:3000"

  mysql:
    image: mysql
    restart: always
