# Docker compose for:
# - Data Ingestion Container
# - MongoDB Container
# Build and execution on local machine (WWSL) with:
# (1) Set environment variable in Dockerfile:
#     ENV HTTPS_PROXY=$https_proxy
# (2) docker-compose build --build-arg "https_proxy=$https_proxy"
# (3) docker-compose up

version: '3.7'
services:
  python-app:
    build: ./data_fetch
    depends_on:
      - mongodb
    #volumes:
    #  - .:/app
  etl-app:
    build: ./etl
   # volumes:
    #  - ./app:/app
    depends_on:
      - mongodb
      - mysql
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mgdbdata:/data/db  
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dba
      MYSQL_PASSWORD: "A1YTsqilzHkUQ4"
      MYSQL_DATABASE: data_db
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3306:3306"
volumes:
  mgdbdata:  


