# Docker compose for:
# - Data Ingestion Container
# - MongoDB Container
# Build and execution on local machine (WWSL) with:
# (1) Set environment variable in Dockerfile:
#     ENV HTTPS_PROXY=$https_proxy
# (2) docker-compose build --build-arg "https_proxy=$https_proxy"
# (3) docker-compose up

version: '3.7'
services:
  python-app:
    build: ./data_fetch
    depends_on:
      - mongodb
    #volumes:
    #  - .:/app
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mgdbdata:/data/db  
volumes:
  mgdbdata:  


