apiVersion: v1
kind: Service
metadata:
  labels:
    app: metabase
  name: metabase-service
  namespace: default
spec:
  ports:
  - nodePort: 32213
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: metabase
  sessionAffinity: None
  type: LoadBalancer