apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  managedFields:
  name: mongodb
  namespace: default
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  sessionAffinity: None
  type: ClusterIP  